# Generated by Django 3.2.20 on 2025-04-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='user',
        ),
        migrations.AddField(
            model_name='website',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
