# Generated by Django 3.0.5 on 2025-04-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20250406_0251'),
    ]

   
