# Generated by Django 3.0.5 on 2025-04-06 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20250406_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='website',
            name='content',
        ),
        migrations.RemoveField(
            model_name='website',
            name='preview_url',
        ),
        migrations.RemoveField(
            model_name='website',
            name='user_id',
        ),
        migrations.AddField(
            model_name='website',
            name='custom_content',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='website',
            name='generated_content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
